---
- name: Install setup dependency.
  apt:
    name: apt-transport-https
    state: installed

- name: Add Wavefront apt repository key.
  apt_key:
    url: https://packagecloud.io/wavefront/proxy-next/gpgkey
    state: present
    validate_certs: no

- name: Add Wavefront Proxy apt repository.
  apt_repository:
    repo: "deb {{ wavefront_proxy_pkg_url }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Add Wavefront Telegraf apt repository.
  apt_repository:
    repo: "deb {{ wavefront_telegraf_pkg_url }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: (wavefront_collector == 'telegraf' && wavefront_install_collector == true)


- name: Ensure Wavefront Proxy is installed.
  apt:
    name: "{{ wavefront_proxy_pkg }}"
    state: "{{ wavefront_proxy_pkg_state }}"
  when: wavefront_install_proxy == true
