---
- name: Ensure Wavefront repo is installed.
  template:
    src: Wavefront.repo.j2
    dest: /etc/yum.repos.d/wavefront.repo
    owner: root
    group: root
    mode: 0644

- name: Add Wavefront repo GPG key.
  rpm_key:
    state: present
    key: https://app.threatstack.com/RPM-GPG-KEY-THREATSTACK
    validate_certs: no

- name: Ensure Wavefront Proxy is installed.
  yum:
    name: "{{ wavefront_proxy_pkg }}"
    state: "{{ wavefront_proxy_pkg_state }}"
    update_cache: yes
  when: wavefront_install_proxy == true
